### ISSUE TITLE
Failed to find provider info for com.nabil.radeon.trajectgps.idsuggestion'

### ISSUE THREAD

**Issue by MuhSalmaNabila** [nglauber/playground#1]
I have a problem after I use your tutorial with my my own database which I set search fiture to filter ID on search bar,it cannot show suggestions and it didn't happen anything when click search. It said 'E/ActivityThread: Failed to find provider info for com.nabil.radeon.trajectgps.idsuggestion'
here is my code :

[IdSuggestionProvider.txt](https://github.com/nglauber/playground/files/434163/IdSuggestionProvider.txt)
[MainActivity.txt](https://github.com/nglauber/playground/files/434164/MainActivity.txt)
[SearchableActivity.txt](https://github.com/nglauber/playground/files/434165/SearchableActivity.txt)

**Comment by nglauber** [comment]
Can you share your project to I take a look?

**Comment by lewersmith** [comment]
Hi, Sir. I am downloading the original source code and try to run in the devices with the original json url, but I can't get any city suggestion when I try to key in the value. May I know the problem? Thank you sir for sharing.

**Comment by nglauber** [comment]
@lewersmith this JSON contains a list of Brazilian cities and was made just to clarify this sample it is not a real service ;)

**Comment by lewersmith** [comment]
Thanks sir for your reply. Ya, I just realize the problem as the android does not return the path suggestion/search_suggest_query. Sir, thanks for your tutorial, its nice and awesome. Sorry for my poor programming knowledge.

**Comment by nglauber** [comment]
You're  welcome @lewersmith! If you have any questions, just let me know ;)

**Comment by lewersmith** [comment]
Sir, if I want to connect it to my database, and I sent the request to my php server, but I cant get the suggestion, is there any wrong in my php code?
[search_restaurant.txt](https://github.com/nglauber/playground/files/573050/search_restaurant.txt)

**Comment by lewersmith** [comment]
![screenshot_20161106-153108 1](https://cloud.githubusercontent.com/assets/16149873/20036049/7ea63218-a436-11e6-8795-c7ec871f85a6.png)
![screenshot_20161106-153230 1](https://cloud.githubusercontent.com/assets/16149873/20036051/8cb9821a-a436-11e6-9310-13e064e0bb08.png)
Sir, May I know is there anyway to pick one of the suggestion (picture 1) in the search suggestion list and jump into the detail list activity (picture 2) that fetch the data from the server? I fetch the data from the server which I convert them into json array only. I able to get the suggestion of restaurant in the database, but when i click into the suggestion, there is nothing happen, cant get into the restaurant detail page. Sir, may you provide me some advises?

**Comment by nglauber** [comment]
hi @lewersmith. yes, you can do it. the main idea here is to have a local list just with the information that you need for give/show the suggestions for your users (eg.: server id and name). Once you clicked on an suggested item, you can go to the next activity, retrieve the server id from your local database and loads the remaining data from the server.
