### ISSUE TITLE
The search icon color is gray. How to set the search icon color to white, for example?

### ISSUE THREAD

**Issue by revolz** [nglauber/playground#2]
I wouldn't call this as an issue. But since this is how GitHub names the discussion forum.

First, I thank you for sharing this code on GitHub. Your Demo Search code is the simplest sample that I found, yet achieves what I would like to do. 

I notice the search icon color is gray. How to set the search icon color to white, for example?
I have done quite a lot of study, unfortunately it doesn't yield good answer for me. I figure it will be quicker to ask @nglauber the original author.
I believe it has something to do related to the Theme, Material Design & Tint.

Could you give me some pointer? Thank you very much.

**Comment by nglauber** [comment]
hi @revolz! You can just change the icon in menu resource file like below.
```
<menu xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:id="@+id/search"
          android:title="@string/hint_search"
          android:icon="@drawable/ic_search"
          app:showAsAction="collapseActionView|ifRoom"
          app:actionViewClass="android.support.v7.widget.SearchView" />
</menu>
```
I made this change and pushed it to repository. Thank you for your comment.

**Comment by revolz** [comment]
Thanks @nglauber for the reply. From what I observe, Android will still tint the pure white icon ic_search with some color, making its appearance on the Android phone *not* in pure white. Is it what you observe also? Is it something related to Android theme, material design & tinting?

**Comment by revolz** [comment]
@nglauber, I believe I found the answer. I documented the answer at http://stackoverflow.com/q/41011070/50050.

Thanks for your sharing, code & reply!

**Comment by nglauber** [comment]
exactly @revolz! my bad! I made a commit in my machine, but I forgot to push it.
https://github.com/nglauber/playground/commit/15f26b02d753e1cccb31e947352c5b944d75be88
