### ISSUE TITLE
estou  tentando rodar a  StarWarsKoltinRX e tive erro

### ISSUE THREAD

**Issue by ghost** [nglauber/playground#3]
![captura de tela 2017-12-02 as 16 39 09](https://user-images.githubusercontent.com/7308528/33521196-2a3970b8-d780-11e7-9b3e-05427b08df45.png)

**Comment by nglauber** [comment]
Oi @neuberfran. Você poderia passar mais detalhes do erro?
Pela imagem e pelo título da issue eu não entendi...

**Comment by ghost** [comment]
@nglauber Obrigado pelo interesse Glauber. Na realidade ai nao ha erro. Pois vi que o app so faz isso mesmo. Gostaria do codigo fonte desse projeto: https://www.youtube.com/watch?v=Xo5Fp4UqXY8&t=596s   para eu poder completar com a parte do coroutines

**Comment by nglauber** [comment]
Opa Neuber, postei a resposta lá no vídeo. Ainda não terminei esse app. O código mais relevante (já com coroutines) está nesse gist.
https://gist.github.com/nglauber/616563985a6a05830eb4ae4d086aa4bc
